### ISSUE TITLE
EU GreenPass

### ISSUE THREAD

**Issue by cdupont** [yuvadm/greenpass#5]
Hello,
can this application verify [EU GreenPass](https://github.com/ehn-dcc-development/hcert-spec)?
It seems that it can't, because EU GreenPass is based on `base45` and `CBOR`, rather than `base64` and `JSON`. 
Please correct me if I am wrong.

**Comment by yuvadm** [comment]
I haven't seen the spec for the EU greenpass, but I suspect these are two different specs and implementations
